[env:wemos_d1_r32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = PaulStoffregen/Encoder@^1.4.4
monitor_speed = 115200
build_src_filter = +<EvkaPosition/>

[env:test_drawwire]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = PaulStoffregen/Encoder@^1.4.4
monitor_speed = 115200
build_src_filter = -<*> +<tests/DrawWireTest/>

[env:test_rotary]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = PaulStoffregen/Encoder@^1.4.4
monitor_speed = 115200
build_src_filter = -<*> +<tests/RotaryEncoderTest/>
