[platformio]
src_dir = firmware

[env:wemos_d1_r32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = PaulStoffregen/Encoder@^1.4.4
monitor_speed = 115200
build_src_filter = +<*> -<DrawWireTest/> -<RotaryEncoderTest/> -<SingleRotaryTest/>

[env:test_drawwire]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = PaulStoffregen/Encoder@^1.4.4
monitor_speed = 115200
build_src_filter = +<*> -<EvkaPosition/> -<RotaryEncoderTest/> -<SingleRotaryTest/>

[env:test_rotary]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = PaulStoffregen/Encoder@^1.4.4
monitor_speed = 115200
build_src_filter = +<*> -<EvkaPosition/> -<DrawWireTest/> -<SingleRotaryTest/>

[env:test_single_rotary]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = PaulStoffregen/Encoder@^1.4.4
monitor_speed = 115200
build_src_filter = +<SingleRotaryTest/>
