"""replay_reader.py — feed recorded frames into DataStore for offline playback."""

import csv
import threading
from pathlib import Path
from typing import List

from .cmd_main import DATA_PREFIX
from .data_store import DataStore
from .parser import ParsedFrame, parse_line


def _frame_from_row(row: dict) -> ParsedFrame:
    return ParsedFrame(
        x_mm=float(row["x_mm"]),
        y_mm=float(row["y_mm"]),
        z_mm=float(row["z_mm"]),
        r_mm=float(row["r_mm"]),
        theta_deg=float(row["theta_deg"]),
        phi_deg=float(row["phi_deg"]),
        is_valid=int(row["is_valid"]),
        frame_count=int(row["frame_count"]),
        ts_ms=int(row["ts_ms"]),
    )


def load_replay_frames(path: str) -> List[ParsedFrame]:
    """Load frames from CSV log or raw firmware DATA stream dump."""
    file_path = Path(path)
    frames: List[ParsedFrame] = []

    try:
        with file_path.open("r", encoding="utf-8-sig") as handle:
            first_line = handle.readline()
            handle.seek(0)

            # Raw serial dump mode: one firmware DATA line per row.
            # utf-8-sig encoding strips BOM automatically; .strip() removes whitespace.
            if first_line.strip().startswith(DATA_PREFIX):
                for line in handle:
                    frame = parse_line(line)
                    if frame is not None:
                        frames.append(frame)
                return frames

            # CSV mode: generated by DataStore logger.
            reader = csv.DictReader(handle)
            required = {
                "x_mm", "y_mm", "z_mm", "r_mm", "theta_deg", "phi_deg",
                "is_valid", "frame_count", "ts_ms",
            }
            if not reader.fieldnames or not required.issubset(set(reader.fieldnames)):
                return frames

            for row in reader:
                try:
                    frames.append(_frame_from_row(row))
                except (TypeError, ValueError):
                    continue
    except (OSError, UnicodeError):
        return frames

    return frames


class ReplayReader(threading.Thread):
    """Feeds in-memory frame list into DataStore at a fixed playback rate."""

    def __init__(self, frames: List[ParsedFrame], fps: float, store: DataStore, source_path: str):
        super().__init__(daemon=True, name="replay-reader")
        self._frames = frames
        self._period_s = 1.0 / max(1.0, fps)
        self._store = store
        self._source_path = source_path
        self._stop_event = threading.Event()

    def stop(self) -> None:
        self._stop_event.set()

    def run(self) -> None:
        self._store.set_connection(True, f"Replay: {self._source_path}")
        self._store.set_info(f"Replay loaded: {len(self._frames)} frames")

        for frame in self._frames:
            if self._stop_event.is_set():
                break
            self._store.push(frame)
            self._stop_event.wait(self._period_s)

        self._store.set_connection(False, "Replay finished")
