"""gui.py — standalone EVKA calibration app.

One full-screen window: connect, watch live position, run every calibration stage.

    python -m tools.calibration.gui                          # open disconnected
    python -m tools.calibration.gui --serial /dev/ttyUSB0
    python -m tools.calibration.gui --tcp 192.168.1.84:8080
    python -m tools.calibration.gui --ws 192.168.1.50

Tabs: Wire / Theta / Phi PPR trials, Endpoint (world<->sensor pairs, PASS/FAIL report,
gated deploy), Points, Commands.

This tool has no software zero on purpose: every captured coordinate is the raw sensor
frame straight off the wire. A display offset would be absorbed into the fit's translation
and silently produce a transform that is only valid while that offset is active.

The report itself is generated by tools/calibration/report.py — the same engine the CLI and
evka_gui use, so all three always agree on the verdict.
"""

from __future__ import annotations

import argparse
import queue
import statistics
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from serial.tools import list_ports

from tools.calibration import report
from tools.position_checker.cmd_display import AXIS_COLORS
from tools.position_checker.cmd_main import (
    CMD_AP_FALLBACK_IP,
    CMD_DEFAULT_PORT,
    CMD_DEFAULT_STA_IP,
    POINT_PREFIX,
)

# Plumbing is imported, not copied — evka_gui/transport.py is the repo's transport hub
# (it re-exports position_checker's TcpClient). Nothing in evka_gui is modified.
from tools.evka_gui.model import (
    CalRotary,
    CalWire,
    command_response_matches,
    ingest_line,
)
from tools.evka_gui.protocol_log import ProtocolLogPane
from tools.evka_gui.session_utils import format_constants_strip, write_saved_points_csv
from tools.evka_gui.transport import SerialLineReader, TcpClient, WsClient, next_backoff

CMD_DEFAULT_WS_PORT = 80
CMD_RESPONSE_TIMEOUT_S = 2.0

ROLE_CALIBRATION = "calibration"
ROLE_VALIDATION = "validation"
ROLE_LABELS = {ROLE_CALIBRATION: "Calibration", ROLE_VALIDATION: "Validation"}

# Where a passing fit gets deployed for position_checker/GUI to consume.
DEPLOY_JSON = report.PROJECT_ROOT / "tools" / "calibration" / "calibration.json"

_COMMANDS = [
    "ZERO", "ZERO_T", "ZERO_P", "ZERO_W", "PING", "STATUS", "RAW_COUNTS",
    "SAVE_POINT", "DEL_POINT", "CONSTANTS", "SAVE_PPR",
]

_CMD_COLORS = {
    "ZERO": "#ffd700", "ZERO_T": "#ffd700", "ZERO_P": "#ffd700", "ZERO_W": "#ffd700",
    "PING": "#00ffff", "STATUS": "#00ffff", "RAW_COUNTS": "#00ffff", "CONSTANTS": "#00ffff",
    "SAVE_POINT": "#00ff88", "DEL_POINT": "#ff4444", "SAVE_PPR": "#8e44ad",
}


def _btn_style(fg: str) -> str:
    return (
        f"QPushButton {{ color: {fg}; border: 1px solid {fg}; padding: 4px 8px;"
        f" background: transparent; border-radius: 3px; }}"
        f"QPushButton:hover {{ background: {fg}22; }}"
        f"QPushButton:disabled {{ color: #555; border-color: #444; background: transparent; }}"
    )


@dataclass
class WireTrial:
    actual_mm: float
    factor: float
    ppr: float


@dataclass
class CalibrationState:
    wire_trials: List[WireTrial] = field(default_factory=list)
    last_theta: Optional[CalRotary] = None
    last_phi: Optional[CalRotary] = None
    constants_line: str = ""


class CalibrationApp(QtWidgets.QMainWindow):
    """Full-screen calibration workstation: connection + live position + all cal stages."""

    def __init__(self, parent=None, session_dir: Optional[Path] = None):
        super().__init__(parent)
        self._transport = None
        self._queue: queue.Queue = queue.Queue()
        self._is_serial = False
        self._is_ws = False
        self._pending_commands: List[Tuple[str, float]] = []
        self._ppr_pending: Optional[Tuple[str, bool, str]] = None
        self._wire_pending: Optional[Tuple[str, float]] = None
        self._reconnect_delay = 0.0
        self._reconnect_attempts = 0

        self._state = CalibrationState()
        self._last_sensor: Tuple[float, float, float] = (0.0, 0.0, 0.0)
        self._has_sensor = False
        self._saved_point_rows: List[Tuple[str, float, float, float]] = []

        self._session_dir = Path(session_dir) if session_dir else report.DEFAULT_SESSION_DIR
        self._points: List[Tuple[str, report.PointPair]] = []
        self._report: Optional[report.GeneratedReport] = None
        self._report_json_bytes: Optional[bytes] = None

        self.setWindowTitle("EVKA Calibration")
        self.resize(1100, 860)
        self._build_ui()
        self.showMaximized()

        self._drain_timer = QtCore.QTimer(self, interval=25, timeout=self._drain)
        self._cmd_timer = QtCore.QTimer(self, interval=200, timeout=self._check_cmd_timeout)
        self._reconnect_timer = QtCore.QTimer(self, singleShot=True, timeout=self._reconnect_attempt)
        self._drain_timer.start()
        self._cmd_timer.start()

        self._set_connected(False)
        self._load_session()

    # ------------------------------------------------------------------- ui
    def _build_ui(self) -> None:
        central = QtWidgets.QWidget()
        self.setCentralWidget(central)
        col = QtWidgets.QVBoxLayout(central)
        col.setSpacing(4)
        col.setContentsMargins(6, 6, 6, 6)

        col.addWidget(self._grp_connection())
        col.addWidget(self._grp_position())

        tabs = QtWidgets.QTabWidget()
        tabs.setDocumentMode(True)
        tabs.addTab(self._build_wire_tab(), "Wire")
        tabs.addTab(self._build_theta_tab(), "Theta")
        tabs.addTab(self._build_phi_tab(), "Phi")
        tabs.addTab(self._build_endpoint_tab(), "Endpoint")
        tabs.addTab(self._grp_points(), "Points")
        tabs.addTab(self._grp_commands(), "Commands")
        col.addWidget(tabs, 1)

        self._constants_lbl = QtWidgets.QLabel("CONSTANTS: —")
        self._constants_lbl.setStyleSheet("color:#888; font-size:10px;")
        self._constants_lbl.setWordWrap(True)
        col.addWidget(self._constants_lbl)

        log_box = QtWidgets.QGroupBox("Protocol Log")
        log_lay = QtWidgets.QVBoxLayout(log_box)
        log_lay.setContentsMargins(4, 4, 4, 4)
        self._protocol_log = ProtocolLogPane(compact=True)
        log_lay.addWidget(self._protocol_log)
        log_box.setMaximumHeight(130)
        col.addWidget(log_box)

        self._lbl_status = QtWidgets.QLabel("Disconnected.")
        self._lbl_status.setStyleSheet("color:#ff4444; font-weight:bold; font-size:10px;")
        col.addWidget(self._lbl_status)

    def _grp_connection(self) -> QtWidgets.QGroupBox:
        g = QtWidgets.QGroupBox("Connection")
        lay = QtWidgets.QGridLayout(g)
        lay.setHorizontalSpacing(4)
        lay.setVerticalSpacing(3)

        self.rb_serial = QtWidgets.QRadioButton("Serial")
        self.rb_tcp = QtWidgets.QRadioButton("WiFi / TCP")
        self.rb_ws = QtWidgets.QRadioButton("WebSocket")
        self.rb_serial.setChecked(True)
        for rb in (self.rb_serial, self.rb_tcp, self.rb_ws):
            rb.toggled.connect(self._sync_conn_fields)

        self.cmb_port = QtWidgets.QComboBox()
        self.cmb_port.setEditable(True)
        self._refresh_ports()
        btn_rescan = QtWidgets.QPushButton("↻")
        btn_rescan.setFixedWidth(30)
        btn_rescan.clicked.connect(self._refresh_ports)
        self.txt_baud = QtWidgets.QLineEdit("115200")

        self.txt_ip = QtWidgets.QLineEdit(CMD_DEFAULT_STA_IP)
        self.txt_ip.setToolTip(f"STA {CMD_DEFAULT_STA_IP} · AP {CMD_AP_FALLBACK_IP}")
        self.txt_tcp_port = QtWidgets.QLineEdit(str(CMD_DEFAULT_PORT))
        self.txt_ws_host = QtWidgets.QLineEdit(CMD_AP_FALLBACK_IP)
        btn_ap = QtWidgets.QPushButton("AP")
        btn_ap.clicked.connect(lambda: self.txt_ip.setText(CMD_AP_FALLBACK_IP))
        btn_sta = QtWidgets.QPushButton("STA")
        btn_sta.clicked.connect(lambda: self.txt_ip.setText(CMD_DEFAULT_STA_IP))

        self.btn_connect = QtWidgets.QPushButton("Connect")
        self.btn_connect.clicked.connect(self._connect)
        self.btn_disconnect = QtWidgets.QPushButton("Disconnect")
        self.btn_disconnect.clicked.connect(self._disconnect)
        self.btn_blink = QtWidgets.QPushButton("BLINK LED")
        self.btn_blink.setToolTip("Send BLINK — status LED flashes if the link is alive")
        self.btn_blink.clicked.connect(lambda: self._send("BLINK"))

        self.btn_connect.setStyleSheet(_btn_style("#00ff88"))
        self.btn_disconnect.setStyleSheet(_btn_style("#ff4444"))
        self.btn_blink.setStyleSheet(_btn_style("#00ffff"))
        btn_ap.setStyleSheet(_btn_style("#4488ff"))
        btn_sta.setStyleSheet(_btn_style("#4488ff"))

        mode_row = QtWidgets.QHBoxLayout()
        mode_row.setContentsMargins(0, 0, 0, 0)
        for rb in (self.rb_serial, self.rb_tcp, self.rb_ws):
            mode_row.addWidget(rb)
        mode_row.addStretch(1)
        mode_w = QtWidgets.QWidget()
        mode_w.setLayout(mode_row)
        lay.addWidget(mode_w, 0, 0, 1, 4)

        serial_row = QtWidgets.QHBoxLayout()
        serial_row.setContentsMargins(0, 0, 0, 0)
        serial_row.addWidget(self.cmb_port, 1)
        serial_row.addWidget(btn_rescan)
        serial_row.addWidget(QtWidgets.QLabel("Baud"))
        serial_row.addWidget(self.txt_baud)
        serial_w = QtWidgets.QWidget()
        serial_w.setLayout(serial_row)
        lay.addWidget(QtWidgets.QLabel("Serial"), 1, 0)
        lay.addWidget(serial_w, 1, 1, 1, 3)

        tcp_row = QtWidgets.QHBoxLayout()
        tcp_row.setContentsMargins(0, 0, 0, 0)
        tcp_row.addWidget(self.txt_ip, 1)
        tcp_row.addWidget(btn_ap)
        tcp_row.addWidget(btn_sta)
        tcp_row.addWidget(QtWidgets.QLabel("Port"))
        tcp_row.addWidget(self.txt_tcp_port)
        tcp_w = QtWidgets.QWidget()
        tcp_w.setLayout(tcp_row)
        lay.addWidget(QtWidgets.QLabel("TCP"), 2, 0)
        lay.addWidget(tcp_w, 2, 1, 1, 3)

        lay.addWidget(QtWidgets.QLabel("WS"), 3, 0)
        lay.addWidget(self.txt_ws_host, 3, 1, 1, 3)

        conn_row = QtWidgets.QHBoxLayout()
        conn_row.setContentsMargins(0, 0, 0, 0)
        for btn in (self.btn_connect, self.btn_disconnect, self.btn_blink):
            conn_row.addWidget(btn)
        conn_row.addStretch(1)
        conn_w = QtWidgets.QWidget()
        conn_w.setLayout(conn_row)
        lay.addWidget(conn_w, 4, 0, 1, 4)
        lay.setColumnStretch(1, 1)
        self._sync_conn_fields()
        return g

    def _grp_position(self) -> QtWidgets.QGroupBox:
        g = QtWidgets.QGroupBox("Live Position (raw sensor frame)")
        lay = QtWidgets.QGridLayout(g)
        lay.setHorizontalSpacing(18)  # a full-width value must not touch the next axis caption
        # Monospace matters at this size: the value updates at 20 Hz, and proportional
        # digits re-flow the row width on every frame. Set via QFont, not a stylesheet —
        # stylesheet fonts land at polish, so fontMetrics here would measure the default.
        big = QtGui.QFont("monospace")
        big.setPixelSize(40)
        big.setBold(True)
        big_width = QtGui.QFontMetrics(big).horizontalAdvance("-9999.99")
        self._axis_labels = {}
        for i, axis in enumerate(("x", "y", "z")):
            cap = QtWidgets.QLabel(axis.upper())
            cap.setStyleSheet(f"color:{AXIS_COLORS[axis]}; font-weight:bold; font-size:20px;")
            lbl = QtWidgets.QLabel("—")
            lbl.setFont(big)
            lbl.setMinimumWidth(big_width)
            self._axis_labels[axis] = lbl
            lay.addWidget(cap, 0, i * 2)
            lay.addWidget(lbl, 0, i * 2 + 1)

        self._lbl_r = QtWidgets.QLabel("R —")
        self._lbl_theta = QtWidgets.QLabel("θ —")
        self._lbl_phi = QtWidgets.QLabel("φ —")
        lay.addWidget(self._lbl_r, 1, 0, 1, 2)
        lay.addWidget(self._lbl_theta, 1, 2, 1, 2)
        lay.addWidget(self._lbl_phi, 1, 4, 1, 2)

        self._lbl_valid = QtWidgets.QLabel("valid: —")
        self._lbl_frame = QtWidgets.QLabel("frame: —")
        self._lbl_ts = QtWidgets.QLabel("ts: —")
        for lbl in (self._lbl_valid, self._lbl_frame, self._lbl_ts):
            lbl.setStyleSheet("color:#888; font-size:10px;")
        lay.addWidget(self._lbl_valid, 2, 0, 1, 2)
        lay.addWidget(self._lbl_frame, 2, 2, 1, 2)
        lay.addWidget(self._lbl_ts, 2, 4, 1, 2)

        self.btn_hwzero = QtWidgets.QPushButton("ZERO (HW)")
        self.btn_hwzero.setToolTip("Send ZERO — re-zero all three encoders on the device")
        self.btn_hwzero.setStyleSheet(_btn_style("#ffd700"))
        self.btn_hwzero.clicked.connect(self._hardware_zero)
        lay.addWidget(self.btn_hwzero, 0, 6, 3, 1)
        lay.setColumnStretch(7, 1)
        return g

    # ------------------------------------------------------------------ wire
    def _build_wire_tab(self) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        lay = QtWidgets.QVBoxLayout(w)
        lay.addWidget(QtWidgets.QLabel(
            "Zero the wire, pull a known distance, RECORD the trial. Repeat, then apply the mean."
        ))
        row = QtWidgets.QHBoxLayout()
        self.btn_zero_wire = QtWidgets.QPushButton("ZERO WIRE")
        self.btn_zero_wire.setStyleSheet(_btn_style("#ffd700"))
        self.btn_zero_wire.clicked.connect(lambda: self._send("ZERO_W"))
        row.addWidget(self.btn_zero_wire)
        row.addWidget(QtWidgets.QLabel("Actual pull (mm)"))
        self._wire_mm = QtWidgets.QLineEdit()
        row.addWidget(self._wire_mm, 1)
        self.btn_record_wire = QtWidgets.QPushButton("RECORD")
        self.btn_record_wire.setStyleSheet(_btn_style("#00ff88"))
        self.btn_record_wire.clicked.connect(self._record_wire)
        row.addWidget(self.btn_record_wire)
        lay.addLayout(row)

        self._wire_result = QtWidgets.QLabel("—")
        lay.addWidget(self._wire_result)

        self._wire_table = QtWidgets.QTableWidget(0, 4)
        self._wire_table.setHorizontalHeaderLabels(["#", "Actual mm", "Factor", "PPR"])
        self._wire_table.horizontalHeader().setStretchLastSection(True)
        lay.addWidget(self._wire_table, 1)

        self._wire_mean = QtWidgets.QLabel("Mean PPR: —")
        self._wire_spread = QtWidgets.QLabel("Spread: —")
        lay.addWidget(self._wire_mean)
        lay.addWidget(self._wire_spread)

        btns = QtWidgets.QHBoxLayout()
        self.btn_wire_apply = QtWidgets.QPushButton("APPLY (RAM)")
        self.btn_wire_apply.clicked.connect(lambda: self._apply_wire(False))
        self.btn_wire_save = QtWidgets.QPushButton("APPLY + SAVE (NVS)")
        self.btn_wire_save.clicked.connect(lambda: self._apply_wire(True))
        btn_clear = QtWidgets.QPushButton("Clear trials")
        btn_clear.clicked.connect(self._clear_wire_trials)
        for b in (self.btn_wire_apply, self.btn_wire_save, btn_clear):
            btns.addWidget(b)
        lay.addLayout(btns)
        return w

    def _record_wire(self) -> None:
        if self._wire_pending is not None:
            self._set_status("Wait for the current CAL_W reply.", "#ffd700")
            return
        try:
            mm = float(self._wire_mm.text())
        except ValueError:
            self._set_status("Pull distance must be numeric.", "#ff4444")
            return
        if mm <= 0:
            self._set_status("Pull distance must be greater than zero.", "#ff4444")
            return
        command = f"CAL_W {mm}".upper()
        self._wire_pending = (command, mm)
        if not self._send(command):
            self._wire_pending = None

    def _refresh_wire_table(self) -> None:
        trials = self._state.wire_trials
        self._wire_table.setRowCount(len(trials))
        for row, t in enumerate(trials):
            for col, text in enumerate(
                (str(row + 1), f"{t.actual_mm:.2f}", f"{t.factor:.4f}", f"{t.ppr:.1f}")
            ):
                self._wire_table.setItem(row, col, QtWidgets.QTableWidgetItem(text))
        if not trials:
            self._wire_mean.setText("Mean PPR: —")
            self._wire_spread.setText("Spread: —")
            return
        pprs = [t.ppr for t in trials]
        mean = statistics.mean(pprs)
        self._wire_mean.setText(f"Mean PPR: {mean:.1f}  (n={len(pprs)})")
        if len(pprs) > 1 and mean:
            spread = (max(pprs) - min(pprs)) / mean * 100.0
            self._wire_spread.setText(f"Spread: {spread:.2f} %")
        else:
            self._wire_spread.setText("Spread: —")

    def _apply_wire(self, save: bool) -> None:
        if not self._state.wire_trials:
            self._set_status("No wire trials recorded.", "#ff4444")
            return
        mean = statistics.mean(t.ppr for t in self._state.wire_trials)
        self._start_ppr_apply(
            f"SET_PPR_WIRE {mean:.2f}", save, f"PPR_WIRE={mean:.2f}",
        )

    def _clear_wire_trials(self) -> None:
        self._state.wire_trials.clear()
        self._refresh_wire_table()
        self._wire_result.setText("—")

    # -------------------------------------------------------------- rotary
    def _build_theta_tab(self) -> QtWidgets.QWidget:
        w, self._theta_result = self._build_rotary_tab("theta")
        return w

    def _build_phi_tab(self) -> QtWidgets.QWidget:
        w, self._phi_result = self._build_rotary_tab("phi")
        return w

    def _build_rotary_tab(self, axis: str) -> Tuple[QtWidgets.QWidget, QtWidgets.QLabel]:
        code = "T" if axis == "theta" else "P"
        w = QtWidgets.QWidget()
        lay = QtWidgets.QVBoxLayout(w)
        lay.addWidget(QtWidgets.QLabel(
            f"Zero {axis}, turn an exact whole number of revolutions, then compute PPR."
        ))
        row = QtWidgets.QHBoxLayout()
        btn_zero = QtWidgets.QPushButton(f"ZERO {axis.upper()}")
        btn_zero.setStyleSheet(_btn_style("#ffd700"))
        btn_zero.clicked.connect(lambda: self._send(f"ZERO_{code}"))
        row.addWidget(btn_zero)
        row.addWidget(QtWidgets.QLabel("Turns"))
        turns = QtWidgets.QLineEdit("1")
        row.addWidget(turns, 1)
        btn_calc = QtWidgets.QPushButton("COMPUTE")
        btn_calc.setStyleSheet(_btn_style("#00ff88"))
        btn_calc.clicked.connect(lambda: self._compute_rotary(code, turns))
        row.addWidget(btn_calc)
        lay.addLayout(row)

        result = QtWidgets.QLabel("—")
        lay.addWidget(result)

        btns = QtWidgets.QHBoxLayout()
        btn_apply = QtWidgets.QPushButton("APPLY (RAM)")
        btn_apply.clicked.connect(lambda: self._apply_rotary(axis, False))
        btn_save = QtWidgets.QPushButton("APPLY + SAVE (NVS)")
        btn_save.clicked.connect(lambda: self._apply_rotary(axis, True))
        btns.addWidget(btn_apply)
        btns.addWidget(btn_save)
        lay.addLayout(btns)
        lay.addStretch(1)
        self._cal_buttons = getattr(self, "_cal_buttons", [])
        self._cal_buttons += [btn_zero, btn_calc, btn_apply, btn_save]
        return w, result

    def _compute_rotary(self, code: str, turns_edit: QtWidgets.QLineEdit) -> None:
        try:
            turns = int(turns_edit.text())
        except ValueError:
            self._set_status("Turns must be a whole integer.", "#ff4444")
            return
        if turns <= 0:
            self._set_status("Turns must be greater than zero.", "#ff4444")
            return
        self._send(f"CAL_{code} {turns}")

    def _apply_rotary(self, axis: str, save: bool) -> None:
        cal = self._state.last_theta if axis == "theta" else self._state.last_phi
        if cal is None:
            self._set_status(f"No {axis} trial computed yet.", "#ff4444")
            return
        self._start_ppr_apply(
            f"SET_PPR_ROTARY {cal.ppr:.2f}", save, f"PPR for {axis}",
        )

    # ------------------------------------------------------------- endpoint
    def _build_endpoint_tab(self) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        lay = QtWidgets.QVBoxLayout(w)
        lay.addWidget(QtWidgets.QLabel(
            "Collect world/sensor pairs, assign each to the calibration or validation set, "
            "then generate the report. Points live in the session folder."
        ))

        form = QtWidgets.QGridLayout()
        self._ep_label = QtWidgets.QLineEdit()
        self._ep_wx = QtWidgets.QLineEdit()
        self._ep_wy = QtWidgets.QLineEdit()
        self._ep_wz = QtWidgets.QLineEdit()
        self._ep_sx = QtWidgets.QLineEdit()
        self._ep_sy = QtWidgets.QLineEdit()
        self._ep_sz = QtWidgets.QLineEdit()
        self._ep_notes = QtWidgets.QLineEdit()
        coords = [
            ("World X", self._ep_wx), ("World Y", self._ep_wy), ("World Z", self._ep_wz),
            ("Sensor X", self._ep_sx), ("Sensor Y", self._ep_sy), ("Sensor Z", self._ep_sz),
        ]
        for i, (name, widget) in enumerate(coords):
            form.addWidget(QtWidgets.QLabel(name), i // 3, (i % 3) * 2)
            form.addWidget(widget, i // 3, (i % 3) * 2 + 1)
        form.addWidget(QtWidgets.QLabel("Label"), 2, 0)
        form.addWidget(self._ep_label, 2, 1)
        form.addWidget(QtWidgets.QLabel("Notes"), 2, 2)
        form.addWidget(self._ep_notes, 2, 3)
        form.addWidget(QtWidgets.QLabel("Add to"), 2, 4)
        self._ep_role = QtWidgets.QComboBox()
        for role in (ROLE_CALIBRATION, ROLE_VALIDATION):
            self._ep_role.addItem(ROLE_LABELS[role], role)
        form.addWidget(self._ep_role, 2, 5)
        lay.addLayout(form)

        btn_row = QtWidgets.QHBoxLayout()
        self.btn_use_sensor = QtWidgets.QPushButton("Use Current Sensor XYZ")
        self.btn_use_sensor.clicked.connect(self._use_current_sensor)
        btn_add = QtWidgets.QPushButton("Add pair")
        btn_add.clicked.connect(self._add_endpoint)
        btn_import = QtWidgets.QPushButton("Import CSV")
        btn_import.clicked.connect(self._import_endpoint)
        btn_delete = QtWidgets.QPushButton("Delete selected")
        btn_delete.clicked.connect(self._delete_selected)
        btn_clear = QtWidgets.QPushButton("Clear")
        btn_clear.clicked.connect(self._clear_endpoint)
        for b in (self.btn_use_sensor, btn_add, btn_import, btn_delete, btn_clear):
            btn_row.addWidget(b)
        lay.addLayout(btn_row)

        self._ep_table = QtWidgets.QTableWidget(0, 9)
        self._ep_table.setHorizontalHeaderLabels([
            "Label", "World X", "World Y", "World Z",
            "Sensor X", "Sensor Y", "Sensor Z", "Set", "Notes",
        ])
        self._ep_table.horizontalHeader().setStretchLastSection(True)
        self._ep_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self._ep_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        lay.addWidget(self._ep_table, 1)

        run_row = QtWidgets.QHBoxLayout()
        btn_report = QtWidgets.QPushButton("Generate report")
        btn_report.setStyleSheet(_btn_style("#00ff88"))
        btn_report.clicked.connect(self._generate_report)
        self._btn_deploy = QtWidgets.QPushButton("Deploy calibration.json")
        self._btn_deploy.setStyleSheet(_btn_style("#8e44ad"))
        self._btn_deploy.clicked.connect(self._deploy_calibration)
        self._btn_deploy.setEnabled(False)
        self._verdict = QtWidgets.QLabel("No report yet.")
        run_row.addWidget(btn_report)
        run_row.addWidget(self._btn_deploy)
        run_row.addWidget(self._verdict, 1)
        lay.addLayout(run_row)

        self._results = QtWidgets.QTextEdit()
        self._results.setReadOnly(True)
        self._results.setFontFamily("monospace")
        self._results.setMinimumHeight(150)
        lay.addWidget(self._results, 1)
        return w

    # --------------------------------------------------------- session files
    def _load_session(self) -> None:
        """Populate the table from the session CSVs — they are the source of truth."""
        try:
            report.ensure_templates(self._session_dir)
            points: List[Tuple[str, report.PointPair]] = []
            for role, name in (
                (ROLE_CALIBRATION, report.CALIBRATION_CSV),
                (ROLE_VALIDATION, report.VALIDATION_CSV),
            ):
                for p in report.load_point_pairs(self._session_dir / name):
                    points.append((role, p))
        except (OSError, ValueError) as exc:
            self._set_status(f"Could not load session: {exc}", "#ff4444")
            return
        self._points = points
        self._refresh_endpoint_table()
        if points:
            self._set_status(f"Loaded {len(points)} points from {self._session_dir}.", "#888888")

    def _save_session(self) -> bool:
        """Rewrite both CSVs from current state.

        Whole-file rewrite keeps add/delete/role-change on one code path — no dirty tracking.
        """
        try:
            report.save_session_sets(
                self._session_dir,
                [p for role, p in self._points if role == ROLE_CALIBRATION],
                [p for role, p in self._points if role == ROLE_VALIDATION],
            )
        except OSError as exc:
            message = f"Could not save session: {exc}"
            self._load_session()
            self._set_status(message, "#ff4444")
            return False
        return True

    def _refresh_endpoint_table(self) -> None:
        self._ep_table.setRowCount(len(self._points))
        for row, (role, p) in enumerate(self._points):
            values = [p.label, *(f"{v:.2f}" for v in p.world), *(f"{v:.2f}" for v in p.sensor)]
            for col, text in enumerate(values):
                self._ep_table.setItem(row, col, QtWidgets.QTableWidgetItem(text))
            combo = QtWidgets.QComboBox()
            for r in (ROLE_CALIBRATION, ROLE_VALIDATION):
                combo.addItem(ROLE_LABELS[r], r)
            combo.setCurrentIndex(0 if role == ROLE_CALIBRATION else 1)
            combo.currentIndexChanged.connect(
                lambda _idx, r=row, c=combo: self._change_role(r, c.currentData())
            )
            self._ep_table.setCellWidget(row, 7, combo)
            self._ep_table.setItem(row, 8, QtWidgets.QTableWidgetItem(p.notes))

    def _change_role(self, row: int, role: str) -> None:
        if not 0 <= row < len(self._points):
            return
        old_role, pair = self._points[row]
        if old_role == role:
            return
        self._points[row] = (role, pair)
        if not self._save_session():
            return
        self._invalidate_report(f"Moved {pair.label} to {ROLE_LABELS[role]} set — regenerate.")

    # ---------------------------------------------------------- point entry
    def _use_current_sensor(self) -> None:
        if not self._has_sensor:
            self._set_status("No live position yet.", "#ff4444")
            return
        x, y, z = self._last_sensor
        self._ep_sx.setText(f"{x:.3f}")
        self._ep_sy.setText(f"{y:.3f}")
        self._ep_sz.setText(f"{z:.3f}")

    def _add_endpoint(self) -> None:
        try:
            world = np.array([
                float(self._ep_wx.text()), float(self._ep_wy.text()), float(self._ep_wz.text()),
            ], dtype=float)
            sensor = np.array([
                float(self._ep_sx.text()), float(self._ep_sy.text()), float(self._ep_sz.text()),
            ], dtype=float)
        except ValueError:
            self._set_status("All six coordinates must be numeric.", "#ff4444")
            return
        label = self._ep_label.text().strip() or f"P{len(self._points) + 1}"
        role = self._ep_role.currentData()
        self._points.append((role, report.PointPair(
            label, world, sensor, self._ep_notes.text().strip(),
        )))
        if not self._save_session():
            return
        self._refresh_endpoint_table()
        self._invalidate_report(
            f"Added {label} to {ROLE_LABELS[role]} set ({len(self._points)} points)."
        )

    def _delete_selected(self) -> None:
        rows = sorted({i.row() for i in self._ep_table.selectedIndexes()}, reverse=True)
        if not rows:
            self._set_status("Select a row to delete.", "#ff4444")
            return
        for row in rows:
            del self._points[row]
        if not self._save_session():
            return
        self._refresh_endpoint_table()
        self._invalidate_report(f"Deleted {len(rows)} point(s).")

    def _import_endpoint(self) -> None:
        path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self, "Import endpoint pairs", "", "CSV (*.csv);;All (*)"
        )
        if not path:
            return
        role = self._ep_role.currentData()
        try:
            # Shares the report parser: BOM-tolerant, and it names bad rows by line number
            # instead of skipping them silently.
            loaded = report.load_point_pairs(Path(path))
        except (OSError, ValueError) as exc:
            self._set_status(f"Import failed: {exc}", "#ff4444")
            return
        if not loaded:
            self._set_status("No rows in CSV.", "#ff4444")
            return
        self._points += [(role, p) for p in loaded]
        if not self._save_session():
            return
        self._refresh_endpoint_table()
        self._invalidate_report(f"Imported {len(loaded)} points into {ROLE_LABELS[role]} set.")

    def _clear_endpoint(self) -> None:
        self._points.clear()
        if not self._save_session():
            return
        self._refresh_endpoint_table()
        self._invalidate_report("Cleared all points.")

    # --------------------------------------------------------------- report
    def _invalidate_report(self, message: str) -> None:
        """Any point change makes the last verdict stale — never leave deploy armed."""
        self._report = None
        self._report_json_bytes = None
        self._btn_deploy.setEnabled(False)
        self._verdict.setText("No report yet.")
        self._verdict.setStyleSheet("")
        self._set_status(message, "#888888")

    def _generate_report(self) -> None:
        self._invalidate_report("Generating report…")
        try:
            generated = report.generate_report(self._session_dir)
        except ValueError as exc:
            self._set_status(str(exc), "#ff4444")
            self._results.setPlainText(str(exc))
            return
        except OSError as exc:
            self._set_status(f"Report failed: {exc}", "#ff4444")
            return
        if generated is None:
            self._set_status(
                "Add at least 3 calibration points and 1 validation point.", "#ff4444"
            )
            return

        try:
            report_json_bytes = generated.calibration_json.read_bytes()
        except OSError as exc:
            self._set_status(f"Report failed: {exc}", "#ff4444")
            return
        self._report = generated
        self._report_json_bytes = report_json_bytes
        passed = generated.passed
        self._verdict.setText("PASS" if passed else "FAIL")
        self._verdict.setStyleSheet(
            "color:#2e7d32; font-weight:bold;" if passed else "color:#c62828; font-weight:bold;"
        )
        self._btn_deploy.setEnabled(passed)
        self._results.setPlainText(self._format_results(generated))
        self._set_status(f"Report written to {generated.report_md}.", "#00ff88" if passed else "#ffd700")

    @staticmethod
    def _format_results(generated: report.GeneratedReport) -> str:
        cal, val = generated.calibration_stats, generated.validation_stats
        lines = [
            f"Calibration  n={cal.n}  RMSE {cal.rmse_mm:.2f} mm  max {cal.max_mm:.2f} mm "
            f"({cal.max_label})  limit RMSE <= {report.CALIBRATION_RMSE_LIMIT_MM:.1f} mm  "
            f"[{'PASS' if report.calibration_passed(cal) else 'FAIL'}]",
            f"Validation   n={val.n}  RMSE {val.rmse_mm:.2f} mm  max {val.max_mm:.2f} mm "
            f"({val.max_label})  limit max <= {report.VALIDATION_MAX_LIMIT_MM:.1f} mm  "
            f"[{'PASS' if report.validation_passed(val) else 'FAIL'}]",
        ]
        for title, errors in (
            ("Calibration points", generated.calibration_errors),
            ("Validation points", generated.validation_errors),
        ):
            lines += ["", title, f"{'label':<12}{'error mm':>10}{'dx':>9}{'dy':>9}{'dz':>9}"]
            for e in errors:
                lines.append(
                    f"{e.label:<12}{e.error_mm:>10.2f}"
                    f"{e.delta[0]:>9.2f}{e.delta[1]:>9.2f}{e.delta[2]:>9.2f}"
                )
        return "\n".join(lines)

    def _deploy_calibration(self) -> None:
        if self._report is None or not self._report.passed:
            self._set_status("Deploy requires a passing report.", "#ff4444")
            return
        reply = QtWidgets.QMessageBox.question(
            self, "Deploy calibration.json",
            f"Overwrite {DEPLOY_JSON} with this passing fit?\n\n"
            f"Calibration RMSE {self._report.calibration_stats.rmse_mm:.2f} mm, "
            f"validation max {self._report.validation_stats.max_mm:.2f} mm.",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
            QtWidgets.QMessageBox.No,
        )
        if reply != QtWidgets.QMessageBox.Yes:
            return
        try:
            if (self._report_json_bytes is None
                    or self._report.calibration_json.read_bytes() != self._report_json_bytes):
                self._invalidate_report("Session calibration.json changed; regenerate the report.")
                return
            DEPLOY_JSON.parent.mkdir(parents=True, exist_ok=True)
            DEPLOY_JSON.write_bytes(self._report_json_bytes)
        except OSError as exc:
            self._set_status(f"Deploy failed: {exc}", "#ff4444")
            return
        self._set_status(f"Deployed to {DEPLOY_JSON}.", "#00ff88")

    # --------------------------------------------------------------- points
    def _grp_points(self) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        lay = QtWidgets.QVBoxLayout(w)
        lay.addWidget(QtWidgets.QLabel(
            "Points saved on the device (SAVE_POINT / pendant). Separate from endpoint pairs."
        ))
        row = QtWidgets.QHBoxLayout()
        self.btn_save_pt = QtWidgets.QPushButton("SAVE POINT")
        self.btn_save_pt.setStyleSheet(_btn_style("#00ff88"))
        self.btn_save_pt.clicked.connect(lambda: self._send("SAVE_POINT"))
        self.btn_del_pt = QtWidgets.QPushButton("DEL LAST POINT")
        self.btn_del_pt.setStyleSheet(_btn_style("#ff4444"))
        self.btn_del_pt.clicked.connect(lambda: self._send("DEL_POINT"))
        btn_export = QtWidgets.QPushButton("Export CSV")
        btn_export.clicked.connect(self._export_saved_points)
        for b in (self.btn_save_pt, self.btn_del_pt, btn_export):
            row.addWidget(b)
        lay.addLayout(row)
        self._pts_list = QtWidgets.QListWidget()
        lay.addWidget(self._pts_list, 1)
        return w

    def _export_saved_points(self) -> None:
        if not self._saved_point_rows:
            self._set_status("No saved points to export.", "#ff4444")
            return
        path, _ = QtWidgets.QFileDialog.getSaveFileName(
            self, "Export saved points", "saved_points.csv", "CSV (*.csv)"
        )
        if not path:
            return
        try:
            n = write_saved_points_csv(path, self._saved_point_rows)
        except OSError as exc:
            self._set_status(f"Export failed: {exc}", "#ff4444")
            return
        self._set_status(f"Exported {n} saved points.", "#00ff88")

    def _grp_commands(self) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        lay = QtWidgets.QVBoxLayout(w)
        lay.addWidget(QtWidgets.QLabel("Send a command straight to the firmware."))
        grid = QtWidgets.QGridLayout()
        self._cmd_buttons = []
        cols = 5
        for i, cmd in enumerate(_COMMANDS):
            b = QtWidgets.QPushButton(cmd)
            b.setStyleSheet(_btn_style(_CMD_COLORS.get(cmd, "#8899aa")))
            b.clicked.connect(lambda _=False, c=cmd: self._send(c))
            self._cmd_buttons.append(b)
            grid.addWidget(b, i // cols, i % cols)
        lay.addLayout(grid)

        row = QtWidgets.QHBoxLayout()
        self._txt_cmd = QtWidgets.QLineEdit()
        self._txt_cmd.setPlaceholderText("Custom command, e.g. SET_PPR_WIRE 8000")
        self._txt_cmd.returnPressed.connect(self._send_custom)
        self.btn_send_cmd = QtWidgets.QPushButton("Send")
        self.btn_send_cmd.clicked.connect(self._send_custom)
        row.addWidget(self._txt_cmd, 1)
        row.addWidget(self.btn_send_cmd)
        lay.addLayout(row)
        lay.addStretch(1)
        return w

    def _send_custom(self) -> None:
        cmd = self._txt_cmd.text().strip()
        if cmd:
            self._send(cmd)

    def _hardware_zero(self) -> None:
        self._send("ZERO")

    # ------------------------------------------------------------ transport
    def _refresh_ports(self) -> None:
        current = self.cmb_port.currentText()
        self.cmb_port.clear()
        for p in list_ports.comports():
            self.cmb_port.addItem(p.device)
        if current:
            self.cmb_port.setEditText(current)

    def _sync_conn_fields(self) -> None:
        serial_mode = self.rb_serial.isChecked()
        tcp_mode = self.rb_tcp.isChecked()
        ws_mode = self.rb_ws.isChecked()
        self.cmb_port.setEnabled(serial_mode)
        self.txt_baud.setEnabled(serial_mode)
        self.txt_ip.setEnabled(tcp_mode)
        self.txt_tcp_port.setEnabled(tcp_mode)
        self.txt_ws_host.setEnabled(ws_mode)

    def _connect(self, *, silent: bool = False) -> None:
        """Connect using the current panel settings.

        ``silent`` is set by the auto-reconnect timer: failures then feed the backoff
        instead of popping a modal dialog in the operator's face.
        """
        if self._transport is not None:
            return

        def fail(msg: str) -> None:
            if silent:
                self._schedule_reconnect(msg)
            else:
                self._warn(msg)

        if self.rb_serial.isChecked():
            port = self.cmb_port.currentText().strip()
            if not port:
                fail("No serial port selected.")
                return
            try:
                baud = int(self.txt_baud.text())
            except ValueError:
                fail("Invalid baud rate.")
                return
            tr = SerialLineReader()
            tr.set_callbacks(on_line=self._push_line, on_disconnect=self._push_disconnect)
            ok, info = tr.connect(port, baud)
            self._is_serial, self._is_ws = True, False
        elif self.rb_ws.isChecked():
            tr = WsClient()
            tr.set_callbacks(on_line=self._push_line, on_disconnect=self._push_disconnect)
            ok, info = tr.connect(self.txt_ws_host.text().strip(), CMD_DEFAULT_WS_PORT)
            self._is_serial, self._is_ws = False, True
        else:
            try:
                port = int(self.txt_tcp_port.text())
            except ValueError:
                fail("Invalid TCP port.")
                return
            tr = TcpClient()
            tr.set_callbacks(on_line=self._push_line, on_disconnect=self._push_disconnect)
            ok, info = tr.connect(self.txt_ip.text().strip(), port)
            self._is_serial, self._is_ws = False, False

        if not ok:
            fail(f"Connection failed: {info}")
            return
        self._transport = tr
        self._cancel_reconnect()
        self._set_connected(True)
        self._set_status("Connected.", "#00ff88")
        self._send("CONSTANTS")

    def _cancel_reconnect(self) -> None:
        """Stop any pending retry and reset the backoff to its first step."""
        self._reconnect_timer.stop()
        self._reconnect_delay = 0.0
        self._reconnect_attempts = 0
        self.btn_disconnect.setText("Disconnect")

    def _schedule_reconnect(self, reason: str) -> None:
        self._reconnect_delay = next_backoff(self._reconnect_delay)
        self._reconnect_attempts += 1
        self._reconnect_timer.start(int(self._reconnect_delay * 1000))
        # The Disconnect button doubles as the escape hatch while we retry.
        self.btn_disconnect.setEnabled(True)
        self.btn_disconnect.setText("Cancel")
        self._set_status(
            f"{reason} — reconnecting in {self._reconnect_delay:.0f}s "
            f"(attempt {self._reconnect_attempts})",
            "#ffd700",
        )

    def _reconnect_attempt(self) -> None:
        self._set_status(f"Reconnecting (attempt {self._reconnect_attempts})…", "#ffd700")
        self._connect(silent=True)

    def _on_link_lost(self, reason: str) -> None:
        self._teardown(reset_backoff=False)
        self._schedule_reconnect(f"Lost link ({reason})")

    def _disconnect(self) -> None:
        """User-initiated disconnect — also cancels any retry in flight."""
        self._teardown(reset_backoff=True)
        self._set_status("Disconnected.", "#ff4444")

    def _teardown(self, *, reset_backoff: bool) -> None:
        if reset_backoff:
            self._cancel_reconnect()
        if self._transport is not None:
            self._transport.close(emit_disconnect=False)
            self._transport = None
        self._reset_ui()
        self._set_connected(False)
        # Caller sets the status line: _disconnect says "Disconnected",
        # _on_link_lost says "reconnecting in Ns".

    def _reset_ui(self) -> None:
        self._clear_pending_cmd()
        self._ppr_pending = None
        self._wire_pending = None
        self._has_sensor = False
        for lbl in self._axis_labels.values():
            lbl.setText("—")
        self._lbl_r.setText("R —")
        self._lbl_theta.setText("θ —")
        self._lbl_phi.setText("φ —")
        self._lbl_valid.setText("valid: —")
        self._lbl_frame.setText("frame: —")
        self._lbl_ts.setText("ts: —")

    def _set_connected(self, connected: bool) -> None:
        self.btn_connect.setEnabled(not connected)
        self.btn_disconnect.setEnabled(connected)
        for rb in (self.rb_serial, self.rb_tcp, self.rb_ws):
            rb.setEnabled(not connected)
        device_buttons = [
            self.btn_blink, self.btn_hwzero, self.btn_zero_wire, self.btn_record_wire,
            self.btn_wire_apply, self.btn_wire_save, self.btn_save_pt, self.btn_del_pt,
            self.btn_send_cmd, self.btn_use_sensor,
            *self._cmd_buttons,
            *getattr(self, "_cal_buttons", []),
        ]
        for b in device_buttons:
            b.setEnabled(connected)

    def _push_line(self, line: str) -> None:
        self._queue.put(("line", line))

    def _push_disconnect(self, reason: str) -> None:
        self._queue.put(("disconnect", reason))

    def _send(self, cmd: str) -> bool:
        if self._transport is None:
            self._warn("Not connected.")
            return False
        command = cmd.strip().upper()
        if command.startswith("CAL_W ") and any(
            pending.startswith("CAL_W ") for pending, _ in self._pending_commands
        ):
            self._set_status("CAL_W already waiting for a reply.", "#ffd700")
            return False
        ok, info = self._transport.send_command(cmd)
        if not ok:
            self._warn(f"Send failed: {info}")
            return False
        self._pending_commands.append((command, time.monotonic()))
        self._set_status(f"Sent {command}, waiting…", "#888888")
        return True

    def _clear_pending_cmd(self) -> None:
        self._pending_commands.clear()

    def _complete_pending_response(self, line: str) -> Optional[str]:
        if not self._pending_commands:
            return None
        index = None
        for i, (command, _) in enumerate(self._pending_commands):
            if command_response_matches(command, line):
                index = i
                break
        if index is None:
            return None
        command, _ = self._pending_commands.pop(index)
        return command

    def _check_cmd_timeout(self) -> None:
        if not self._pending_commands:
            return
        now = time.monotonic()
        expired = [
            command for command, sent_at in self._pending_commands
            if now - sent_at >= CMD_RESPONSE_TIMEOUT_S
        ]
        if not expired:
            return
        self._pending_commands = [
            item for item in self._pending_commands
            if now - item[1] < CMD_RESPONSE_TIMEOUT_S
        ]
        for command in expired:
            self._handle_command_timeout(command)
        self._set_status(
            f"No response to {', '.join(expired)} (timeout)", "#ff4444",
        )

    def _drain(self) -> None:
        """Runs on the GUI thread — transport callbacks only ever enqueue."""
        while True:
            try:
                kind, payload = self._queue.get_nowait()
            except queue.Empty:
                break
            if kind == "disconnect":
                # A disconnect event with no transport is an echo of a close that already
                # happened; acting on it would auto-reconnect against the user's wish.
                if self._transport is not None:
                    self._on_link_lost(str(payload))
                    return
                continue
            if self._protocol_log is not None:
                self._protocol_log.append_line(payload)
            replied_cmd = self._complete_pending_response(payload)
            for up in ingest_line(payload):
                self._apply(up, replied_cmd)

    def _apply(self, up, replied_cmd: Optional[str] = None) -> None:
        k, d = up.kind, up.data
        if k == "position":
            self._on_position(*d)
        elif k == "sensor":
            self._on_sensor(*d)
        elif k == "ts":
            self._lbl_ts.setText(f"ts: {d} ms")
        elif k == "point":
            self._on_point(d)
        elif k == "del_point":
            self._on_del_point(d)
        elif k == "ack":
            self._on_ack(d, replied_cmd)
        elif k == "err":
            self._on_err(d, replied_cmd)
        elif k == "cal":
            self._on_cal(d, replied_cmd)
        elif k == "constants":
            self._on_constants(d)

    # ------------------------------------------------------------- handlers
    def _on_position(self, x: float, y: float, z: float) -> None:
        # Raw wire values — this app has no software-zero path, so what an operator
        # captures is exactly what the sensor reported.
        self._last_sensor = (x, y, z)
        self._has_sensor = True
        self._axis_labels["x"].setText(f"{x:.2f}")
        self._axis_labels["y"].setText(f"{y:.2f}")
        self._axis_labels["z"].setText(f"{z:.2f}")

    def _on_sensor(self, r, theta, phi, valid, frame) -> None:
        self._lbl_r.setText(f"R {r:.2f}")
        self._lbl_theta.setText(f"θ {theta:.2f}")
        self._lbl_phi.setText(f"φ {phi:.2f}")
        self._lbl_valid.setText(f"valid: {'✓' if valid else '✗'}")
        self._lbl_frame.setText(f"frame: {frame}")

    def _on_constants(self, line: str) -> None:
        self._state.constants_line = line
        self._constants_lbl.setText(f"CONSTANTS: {format_constants_strip(line)}")

    def _on_cal(self, cal, replied_command: Optional[str] = None) -> None:
        if isinstance(cal, CalWire):
            if self._wire_pending is None or replied_command != self._wire_pending[0]:
                return
            _, actual_mm = self._wire_pending
            self._wire_pending = None
            self._state.wire_trials.append(
                WireTrial(actual_mm, cal.factor, cal.ppr_wire)
            )
            self._wire_result.setText(f"Trial: factor={cal.factor:.4f}, PPR={cal.ppr_wire:.1f}")
            self._refresh_wire_table()
        elif isinstance(cal, CalRotary):
            expected = "CAL_T " if cal.axis == "theta" else "CAL_P "
            if replied_command is None or not replied_command.startswith(expected):
                return
            if cal.axis == "theta":
                self._state.last_theta = cal
                self._theta_result.setText(f"Counts={cal.counts}, PPR={cal.ppr:.1f}")
            else:
                self._state.last_phi = cal
                self._phi_result.setText(f"Counts={cal.counts}, PPR={cal.ppr:.1f}")

    def _on_point(self, line: str) -> None:
        parts = line[len(POINT_PREFIX):].split(",")
        if len(parts) < 4:
            return
        try:
            idx, wx, wy, wz = parts[0], float(parts[1]), float(parts[2]), float(parts[3])
        except ValueError:
            return
        self._saved_point_rows.append((idx, wx, wy, wz))
        self._pts_list.addItem(f"#{idx}: {wx:.2f}, {wy:.2f}, {wz:.2f} mm")

    def _on_del_point(self, line: str) -> None:
        if self._pts_list.count():
            self._pts_list.takeItem(self._pts_list.count() - 1)
        if self._saved_point_rows:
            self._saved_point_rows.pop()

    def _start_ppr_apply(self, command: str, save: bool, label: str) -> None:
        if self._ppr_pending is not None:
            self._set_status("Wait for the current PPR command reply.", "#ffd700")
            return
        self._ppr_pending = (command, save, label)
        if not self._send(command):
            self._ppr_pending = None
            return
        self._set_status(f"Waiting for {command.split()[0]} reply…", "#888888")

    def _handle_ppr_reply(self, line: str, replied_command: Optional[str]) -> None:
        pending = self._ppr_pending
        if pending is None:
            return
        command, save, label = pending
        if line.startswith("ERR:"):
            if replied_command != command:
                return
            self._ppr_pending = None
            self._set_status(f"{label} failed: {line}", "#ff4444")
            return
        if not command_response_matches(command, line):
            return
        if save and command != "SAVE_PPR":
            self._ppr_pending = ("SAVE_PPR", False, label)
            if not self._send("SAVE_PPR"):
                self._ppr_pending = None
                return
            self._set_status(f"{label} applied; waiting for SAVE_PPR reply…", "#888888")
            return
        self._ppr_pending = None
        self._set_status(
            f"{'Saved' if command == 'SAVE_PPR' else 'Applied'} {label}", "#00ff88",
        )

    def _handle_command_timeout(self, command: str) -> None:
        if self._wire_pending is not None and self._wire_pending[0] == command:
            self._wire_pending = None
        if self._ppr_pending is not None and self._ppr_pending[0] == command:
            self._ppr_pending = None

    def _on_ack(self, line: str, replied_command: Optional[str] = None) -> None:
        if line.startswith(("ACK:PPR_", "ACK:SAVE_PPR")) and replied_command is None:
            self._set_status(f"Unexpected reply: {line}", "#ffd700")
        else:
            self._set_status(line, "#00ff88")
        self._handle_ppr_reply(line, replied_command)

    def _on_err(self, line: str, replied_command: Optional[str] = None) -> None:
        self._set_status(line, "#ff4444")
        if (self._wire_pending is not None
                and replied_command == self._wire_pending[0]):
            self._wire_pending = None
        self._handle_ppr_reply(line, replied_command)

    # --------------------------------------------------------------- status
    def _set_status(self, text: str, color: str = "#888888") -> None:
        self._lbl_status.setText(text)
        self._lbl_status.setStyleSheet(f"color:{color}; font-weight:bold; font-size:10px;")

    def _warn(self, msg: str) -> None:
        self._set_status(msg, "#ff4444")
        QtWidgets.QMessageBox.warning(self, "Calibration", msg)

    def closeEvent(self, ev) -> None:
        for t in (self._drain_timer, self._cmd_timer, self._reconnect_timer):
            t.stop()
        if self._transport is not None:
            self._transport.close(emit_disconnect=False)
            self._transport = None
        super().closeEvent(ev)


def _parse(argv=None) -> dict:
    p = argparse.ArgumentParser(prog="tools.calibration.gui", description=__doc__)
    g = p.add_mutually_exclusive_group()
    g.add_argument("--serial", metavar="PORT", help="serial port, e.g. /dev/ttyUSB0 or COM3")
    g.add_argument("--tcp", metavar="HOST[:PORT]", help=f"TCP host, default port {CMD_DEFAULT_PORT}")
    g.add_argument("--ws", metavar="HOST", help="WebSocket host (port 80, path /ws)")
    p.add_argument("--baud", type=int, default=115200, help="serial baud (default 115200)")
    p.add_argument("--session", metavar="DIR", help="session folder (default docs/calibration/sessions/current)")
    return vars(p.parse_args(argv))


def main(argv=None) -> int:
    args = _parse(argv)
    app = QtWidgets.QApplication(sys.argv[:1])
    win = CalibrationApp(session_dir=Path(args["session"]) if args["session"] else None)

    if args["serial"]:
        win.rb_serial.setChecked(True)
        win.cmb_port.setEditText(args["serial"])
        win.txt_baud.setText(str(args["baud"]))
    elif args["tcp"]:
        host, _, port = args["tcp"].partition(":")
        win.rb_tcp.setChecked(True)
        win.txt_ip.setText(host)
        win.txt_tcp_port.setText(port or str(CMD_DEFAULT_PORT))
    elif args["ws"]:
        win.rb_ws.setChecked(True)
        win.txt_ws_host.setText(args["ws"])

    win.show()
    if args["serial"] or args["tcp"] or args["ws"]:
        QtCore.QTimer.singleShot(0, win._connect)
    return app.exec_()


if __name__ == "__main__":
    raise SystemExit(main())
